from app.models.roles import Role
from app.models.users import Users
from app.models.module import Module
from app.models.actions import Actions
from app.models.role_actions import Role_Actions
from app.utilities.hashing import Hash
from test import uuids_for_test

all_actions = [
    Role(
        id=uuids_for_test.role_uuid,
        name="test_admin",
        description="test_admin",
    ),
    Role(id=uuids_for_test.second_role_uuid, name="test_user", description="test role"),
    Users(
        id=uuids_for_test.user_uuid,
        email=uuids_for_test.user_email,
        password=Hash().bcrypt(f"{uuids_for_test.user_password}"),
        is_active=True,
        role_id=uuids_for_test.role_uuid,
    ),
    Users(
        id=uuids_for_test.second_user_uuid,
        email=uuids_for_test.second_user_email,
        password=Hash().bcrypt(f"{uuids_for_test.second_user_password}"),
        is_active=True,
        role_id=uuids_for_test.role_uuid,
    ),
    Module(
        id=uuids_for_test.module_user_uuid,
        name="users",
        description="module for Users",
    ),
    Module(
        id=uuids_for_test.module_role_uuid,
        name="roles",
        description="module for Roles",
    ),
    Module(
        id=uuids_for_test.module_action_uuid,
        name="actions",
        description="module for Actions",
    ),
    Module(
        id=uuids_for_test.module_module_uuid,
        name="modules",
        description="module for modules",
    ),
    Module(
        id=uuids_for_test.module_permissions_uuid,
        name="permissions",
        description="module for Permissions",
    ),
    Module(
        id=uuids_for_test.module_premiun_uuid,
        name="premiun",
        description="module for premiun module",
    ),
    Actions(
        id=uuids_for_test.action_create_permissions_uuid,
        action_name="create",
        is_active=True,
        description="create action for permissions module",
        module_id=uuids_for_test.module_permissions_uuid,
    ),
    Actions(
        id=uuids_for_test.action_read_permissions_uuid,
        action_name="read",
        is_active=True,
        description="read action for permissions module",
        module_id=uuids_for_test.module_permissions_uuid,
    ),
    Actions(
        id=uuids_for_test.action_update_permissions_uuid,
        action_name="update",
        is_active=True,
        description="update action for permissions module",
        module_id=uuids_for_test.module_permissions_uuid,
    ),
    Actions(
        id=uuids_for_test.action_delete_permissions_uuid,
        action_name="delete",
        is_active=True,
        description="delete action for permissions module",
        module_id=uuids_for_test.module_permissions_uuid,
    ),
    Actions(
        id=uuids_for_test.action_search_permissions_uuid,
        action_name="search",
        is_active=True,
        description="search action for permissions module",
        module_id=uuids_for_test.module_permissions_uuid,
    ),
    Actions(
        id=uuids_for_test.action_create_modules_uuid,
        action_name="create",
        is_active=True,
        description="create action for modules module",
        module_id=uuids_for_test.module_module_uuid,
    ),
    Actions(
        id=uuids_for_test.action_read_modules_uuid,
        action_name="read",
        is_active=True,
        description="read action for modules module",
        module_id=uuids_for_test.module_module_uuid,
    ),
    Actions(
        id=uuids_for_test.action_upate_modules_uuid,
        action_name="update",
        is_active=True,
        description="update action for modules module",
        module_id=uuids_for_test.module_module_uuid,
    ),
    Actions(
        id=uuids_for_test.action_delete_modules_uuid,
        action_name="delete",
        is_active=True,
        description="delete action for modules module",
        module_id=uuids_for_test.module_module_uuid,
    ),
    Actions(
        id=uuids_for_test.action_search_modules_uuid,
        action_name="search",
        is_active=True,
        description="search action for modules module",
        module_id=uuids_for_test.module_module_uuid,
    ),
    Actions(
        id=uuids_for_test.action_create_actions_uuid,
        action_name="create",
        is_active=True,
        description="create action for actions module",
        module_id=uuids_for_test.module_action_uuid,
    ),
    Actions(
        id=uuids_for_test.action_read_actions_uuid,
        action_name="read",
        is_active=True,
        description="read action for actions module",
        module_id=uuids_for_test.module_action_uuid,
    ),
    Actions(
        id=uuids_for_test.action_upate_actions_uuid,
        action_name="update",
        is_active=True,
        description="update action for actions module",
        module_id=uuids_for_test.module_action_uuid,
    ),
    Actions(
        id=uuids_for_test.action_delete_actions_uuid,
        action_name="delete",
        is_active=True,
        description="delete action for actions module",
        module_id=uuids_for_test.module_action_uuid,
    ),
    Actions(
        id=uuids_for_test.action_search_actions_uuid,
        action_name="search",
        is_active=True,
        description="search action for actions module",
        module_id=uuids_for_test.module_action_uuid,
    ),
    Actions(
        id=uuids_for_test.action_create_roles_uuid,
        action_name="create",
        is_active=True,
        description="create action for roles module",
        module_id=uuids_for_test.module_role_uuid,
    ),
    Actions(
        id=uuids_for_test.action_read_roles_uuid,
        action_name="read",
        is_active=True,
        description="read action for roles module",
        module_id=uuids_for_test.module_role_uuid,
    ),
    Actions(
        id=uuids_for_test.action_upate_roles_uuid,
        action_name="update",
        is_active=True,
        description="update action for roles module",
        module_id=uuids_for_test.module_role_uuid,
    ),
    Actions(
        id=uuids_for_test.action_delete_roles_uuid,
        action_name="delete",
        is_active=True,
        description="delete action for roles module",
        module_id=uuids_for_test.module_role_uuid,
    ),
    Actions(
        id=uuids_for_test.action_search_roles_uuid,
        action_name="search",
        is_active=True,
        description="search action for roles module",
        module_id=uuids_for_test.module_role_uuid,
    ),
    Actions(
        id=uuids_for_test.action_create_users_uuid,
        action_name="create",
        is_active=True,
        description="create action for users module",
        module_id=uuids_for_test.module_user_uuid,
    ),
    Actions(
        id=uuids_for_test.action_read_users_uuid,
        action_name="read",
        is_active=True,
        description="read action for users module",
        module_id=uuids_for_test.module_user_uuid,
    ),
    Actions(
        id=uuids_for_test.action_upate_users_uuid,
        action_name="update",
        is_active=True,
        description="update action for users module",
        module_id=uuids_for_test.module_user_uuid,
    ),
    Actions(
        id=uuids_for_test.action_delete_users_uuid,
        action_name="delete",
        is_active=True,
        description="delete action for users module",
        module_id=uuids_for_test.module_user_uuid,
    ),
    Actions(
        id=uuids_for_test.action_search_users_uuid,
        action_name="search",
        is_active=True,
        description="search action for users module",
        module_id=uuids_for_test.module_user_uuid,
    ),
    Actions(
        id=uuids_for_test.action_create_premiun_uuid,
        action_name="create",
        is_active=True,
        description="create action for premiun module",
        module_id=uuids_for_test.module_premiun_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_create_permission_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_create_permissions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_read_permission_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_read_permissions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_update_permission_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_update_permissions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_delete_permission_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_delete_permissions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_search_permission_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_search_permissions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_create_premiun_uuid,
        role_id=uuids_for_test.second_role_uuid,
        actions_id=uuids_for_test.action_create_premiun_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_create_modules_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_create_modules_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_read_modules_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_read_modules_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_update_modules_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_upate_modules_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_delete_modules_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_delete_modules_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_search_modules_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_search_modules_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_create_actions_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_create_actions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_read_actions_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_read_actions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_update_actions_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_upate_actions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_delete_actions_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_delete_actions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_search_actions_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_search_actions_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_create_roles_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_create_roles_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_read_roles_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_read_roles_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_update_roles_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_upate_roles_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_delete_roles_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_delete_roles_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_search_roles_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_search_roles_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_create_users_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_create_users_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_read_users_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_read_users_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_update_users_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_upate_users_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_delete_users_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_delete_users_uuid,
    ),
    Role_Actions(
        id=uuids_for_test.permission_search_users_uuid,
        role_id=uuids_for_test.role_uuid,
        actions_id=uuids_for_test.action_search_users_uuid,
    ),
]
